### PR TITLE
feat: implement Go Modules build

### PR DESCRIPTION
**Pull request by alex1989hu**
**Description**
Implement Go Modules build to let dependant repository also migrate to Go Modules build

### CODE REVIEW

**Comment by dsu-igeek** [comment]
Thanks Alex!  Looks good, but I need to hold this off for a while until we get our dependent project into Git modules as well.

**Comment by alex1989hu** [comment]
> Thanks Alex! Looks good, but I need to hold this off for a while until we get our dependent project into Git modules as well.

Your welcome. Could you tell me what are those repositories? - I could help in making them to use Go Modules.

**Comment by alex1989hu** [comment]
Oh, new CI has been added via 4c576a14588f8aca54b5e by @lintongj . This should be also updated but to be honest this YAML is very strange for me, a little help is needed once you can start `astrolabe` using Go Modules.

**Comment by dsu-igeek** [comment]
Thanks Alex - I made some changes and merged your changes via a different PR.

**Pull request closed without merging**
