### PR TITLE
Moved IVD (vSphere virtual disks) to the Velero Plugin for vSphere

### PR DESCRIPTION
**Pull request by dsu-igeek**
Removed IVD and vSphere related build stuff

Signed-off-by: Dave Smith-Uchida <dsmithuchida@vmware.com>

### CODE REVIEW

**Review by deepakkinni — APPROVED** [review]
lgtm

**Comment by lintongj** [comment]
Do you plan to remove code under pkg/common/vsphere as well?

**Comment by dsu-igeek** [comment]
> Do you plan to remove code under pkg/common/vsphere as well?

Good catch, I forgot about that.

**Review by lintongj — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
