### PR TITLE
Updated the cp command in astrolabe cli and added the overwrite command to support overwriting an existing PE with a zip file

### PR DESCRIPTION
**Pull request by lintongj**
The following change are included.
1. Updated the cp command in astrolabe cli to support copying from zip file to a protected entity
2. Updated the implementation of the command, cp, by moving away the detail about zip PE.

Testing:

Below is the config directory. The path of config directory is of your choice.
```
$tree ~/astrolabe/
/home/lintongj/astrolabe/
├── pes
│   └── ivd.pe.json
└── s3config.json
```

1. Copy from PE snapshot to zip file. Below is an example command.
```
astrolabe --confDir ~/astrolabe cp ivd:5d69f3df-2709-4472-9c13-919770f87ea5:2a2b2ff9-e0ee-4a21-a0a0-654f2f4789ad /tmp/destfile10mi.zip
```

2. Overwrite from zip file to an existing PE. Below is an example command.
```
./cmd/astrolabe/astrolabe --confDir ~/astrolabe overwrite /tmp/destfile10mi.zip ivd:fdcc8163-e7a4-43f8-935e-b3ddcdcf6278
```
3. Overwrite from zip file to a unexisted PE. The command fails with error message as below.
```
Could not retrieve info for ivd:fdcc8163-e7a4-43f8-935e-b3ddcdcf6273, err: Retrieve failed: ServerFaultCode: NotFound
```

### CODE REVIEW

**Comment by lintongj** [comment]
Hi Dave@dsu-igeek, the `overwrite` command can alternatively be incorporated into the existing `cp` command, which is equivalent to the case that copying from a source file to a destination PE. Would you please share your thoughts which way is better?

**Comment by dsu-igeek** [comment]
We currently have overwrite and cp.  In the current model creates a new PE.  I think this code will fail if the PE does not already exist.  Let's add cp and overwrite and have them call the equivalent calls.

**Comment by lintongj** [comment]
Hi Dave@dsu-igeek, I resolved your comment and updated code. Please take another look. Thanks.

**Review by dsu-igeek — APPROVED** [review]
LGTM

**Pull request merged**
